package rules

import com.jeillysson.ufal.sistemaespecialista.model.Localizacao

rule "Auditorio para Auditorio"
	when
		ObjetoLoc: Localizacao(saida == 3, destino == 3)
	then
		String mensagem = "<strong>Parabe&#769ns</strong> Voce&#770 Chegou ao Seu Destino!";
		ObjetoLoc.setOrientacao(mensagem); 
end

rule "Auditorio para Locais a Direita"
	when
		ObjetoLoc: Localizacao(saida == 3, destino == 4 || destino == 5 || 
		destino == 6 || destino == 7 || destino == 8 || destino == 9 || destino == 10)
	then
		String local = ObjetoLoc.pegarLocal(ObjetoLoc.getDestino() - 1);
		String mensagem = "Destino <strong>"+local+"<br>1</strong>- Siga pelo corredor que da&#769 acesso ao audito&#769rio<br><br>"+
		"<strong>2</strong> - Depois dobre a sua <strong>DIREITA</strong><br><br>"+
		"<strong>3</strong> - Siga em frente ate&#769 o primeiro corredor de Salas de Aulas, <em>que e&#769 o Bloco A</em><br><br>"+
		"<em>Voce&#770 chegou no Bloco A?</em>";
		ObjetoLoc.setSaida(ObjetoLoc.getSaida()+1);
		ObjetoLoc.setOrientacao(mensagem);	
end

rule "Auditorio para Locais a Esquerda"
	when
		ObjetoLoc: Localizacao(saida == 3, destino == 1 || destino == 2)
	then
		String local = ObjetoLoc.pegarLocal(ObjetoLoc.getDestino() - 1);
		String mensagem = "Destino <strong>"+local+"<br>1</strong> - Siga pelo corredor que da&#769 acesso ao audito&#769rio<br><br>"+
		"<strong>2</strong> - Depois dobre a sua <strong>ESQUERDA</strong><br><br>"+
		"<strong>3</strong> - Siga em frente ate&#769 o proximo Bloco, <em>que e&#769 o Bloco das Coordenaco&#771es</em><br><br>"+
		"<em>Voce&#770 encontrou o Bloco das Coordenaco&#771es?<em>";
		ObjetoLoc.setSaida(ObjetoLoc.getSaida()-1);
		ObjetoLoc.setOrientacao(mensagem);	
end